### ISSUE TITLE
vue中不同路径sass引用，图片路径问题解决办法

### ISSUE THREAD

**Issue by CodeDreamfy** [CodeDreamfy/CodeDemo#6]
### 问题
假设有a、b两个不同路径下的 sass 文件，a 引用 b。以 b.sass 为相对路径引用图片，FIS在编译 a 文件时不能准确找到图片路径

### 解析
流程上是，sass插件先把sass/scss代码编译成css，然后webpack处理css中的路径，这个时候相对位置关系已经发生了变化。

### 解决方案

* 方法一：在b中写绝对路径。绝对路径以 / 开头，相对于项目根目录定位资源（fis-conf.js 所在目录）。这样无论在a还是b中都是正确的路径。

* 方法二：让b中的图片地址变成变量或者mixin的参数，由a在import之后调用传参，相对路径就以a为准了。比如：
```scss
// b.scss
@mixin icon($img) {
    background: url($img);
}
```
```scss
// a.scss
@import "b";
.foo {
    @include icon(a.png);
}
```
* 方法三：借助模块化框架，声明a依赖于b，框架会在需要a的时候先加载b，而不是通过sass的import合并在一起。

### 参考
> https://github.com/fex-team/fis-parser-sass/issues/16
